### ISSUE TITLE
Speed up writing of NetCDF map

### ISSUE THREAD

**Issue by Jerry-Ma** [toltec-astro/macana2#4]
it seems to take longer time to write out the beammaps

**Comment by GrantWWilson** [comment]
I think that Michael has cracked this problem.  Do you want to report Michael?

**Comment by mmccrackan** [comment]
Yeah, Zhiyuan just added the issue so we make sure we're keeping track of things.

Issue resolved and changes have been committed.  Was due to unused code that I believe had to be moved around every time a new signal or weight beammap was saved.
